version: '3.8'
services:
    jenkins:
        image: jenkins/jenkins:lts
        privileged: true
        user: root
        ports:
           - 1234:8080
           - 5000:5000
        container_name: jenkins
        volumes:
           -  /home/Wambugu/jenkins_compose/jenkins_configuration:/var/jenkins_home
           - /var/run/docker.sock:/var/run/docker.sock
  
    agent:
         image: jenkins/ssh-agent:jdk11
         privileged: true
         user: root
         expose:
           - 22
         container_name: agent
         environment:
            - JENKINS_AGENT_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDMjyHKiGRlfv5twN9AWh9dSEdmAD5iyi0SRqXXKuWXlGEwaLlWxxjoSGy0P82iRLCgv0Jnp/N5B3qsx8OA7yB3cNSI7QQCB0rur3GLX+4E75oymi1qYlHyCR5wF/8I4mK11dAaY/vKs8gJzylx/xZWyPlAQDAB8vtXUA9LXPuiFmfoGtCk05JMUQiuEUCMURsYSfZ+cTmGNisViHnv3zoAaftQIA+I8XYQv+190JdO+1mL0HZjNtAnkczePeGCiB0al61gdH9t6chlc453enm5jOzgoSFUbVPWqAVRhaR685cek/ZT4agNpaHUCLpqZF5N+WSTi1QjARStsE/Edvv3q7hFXtkwE6G+vR2c+DyvoAAKeriwWdRH1KYRB31RvzJptmgYT4OJAKF3FW4M4my+P8KF7bYuZEFxIYrQ9PkkIiolaLvffnmWDxToOyaD7J7scv2dYg8DPjiGaqT9RtlAILoEmpzpOtPr3UbvAUd62mL2ISwnNyMQe7ntTGub9Rc= josph@JOS-WAMBUGU

