version: '3.8'
services:
    jenkins:
        image: jenkins/jenkins:lts
        privileged: true
        user: root
        ports:
           - 1234:8080
           - 5000:5000
        container_name: jenkins
        volumes:
           -  /home/Wambugu/jenkins_compose/jenkins_configuration:/var/jenkins_home
           - /var/run/docker.sock:/var/run/docker.sock
  
    agent:
         image: jenkins/ssh-agent:jdk11
         privileged: true
         user: root
         expose:
           - 22
         container_name: agent
         environment:
            - JENKINS_AGENT_SSH_PUBKEY=${MY_SECRET}
